#!/usr/bin/env ruby


git_bundles = %w{
  git://github.com/kien/ctrlp.vim.git
  git://github.com/tpope/vim-endwise.git
  git://github.com/tpope/vim-fugitive.git
  git://github.com/tpope/vim-haml.git
  git://github.com/tpope/vim-rails.git
  git://github.com/vim-ruby/vim-ruby.git
  git://github.com/Lokaltog/vim-powerline.git
  git://github.com/Valloric/YouCompleteMe.git
  git://github.com/tpope/vim-sensible.git
  git://github.com/tomtom/tcomment_vim.git
  git://github.com/scrooloose/syntastic.git
  git://github.com/cakebaker/scss-syntax.vim.git
  git://github.com/tristen/vim-sparkup.git
  git://github.com/jiangmiao/auto-pairs.git
}

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.rm_rf(bundles_dir)
FileUtils.mkdir(bundles_dir)
FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  puts url
  `git clone -q #{url}`
end

Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }
